# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jC0g4GYcsBF-3mn_6qcsFqZ2O9IF6VCG
"""

def is_subset_sum(set, sum):

  n = len(set)
  dp = [[False] * (sum + 1) for _ in range(n + 1)]

  for i in range(n + 1):
    dp[i][0] = True

  for i in range(1, n + 1):
    for j in range(1, sum + 1):

      if set[i - 1] > j:
        dp[i][j] = dp[i - 1][j]
      else:

        dp[i][j] = dp[i - 1][j] or dp[i - 1][j - set[i - 1]]

  return dp[n][sum]

if __name__ == "__main__":
  set = [3, 34, 4, 12, 5, 2]
  sum1 = 9
  sum2 = 30

  if is_subset_sum(set, sum1):
    print("Subset with sum", sum1, "exists.")
  else:
    print("Subset with sum", sum1, "does not exist.")

  if is_subset_sum(set, sum2):
    print("Subset with sum", sum2, "exists.")
  else:
    print("Subset with sum", sum2, "does not exist.")