# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jC0g4GYcsBF-3mn_6qcsFqZ2O9IF6VCG
"""

def count_a(s, n):

  count = s.count('a')
  remainder = n % len(s)

  return count * (n // len(s)) + s[:remainder].count('a')


s = "aba"
n = 10
count = count_a(s, n)
print(count)