# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jC0g4GYcsBF-3mn_6qcsFqZ2O9IF6VCG
"""

def nearest_sum(arr, target):

  nearest_sum = 0


  for i in range(1 << len(arr)):

    current_sum = 0
    for j in range(len(arr)):
      if (i >> j) & 1:
        current_sum += arr[j]


    if current_sum <= target and current_sum > nearest_sum:
      nearest_sum = current_sum


  return nearest_sum


arr = [2, 3, 4]
target = 10

nearest_sum = nearest_sum(arr, target)

print(f"The nearest sum to {target} that can be created using elements of the array is {nearest_sum}")